# Generated by Django 3.2.9 on 2021-12-13 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 23, 28, 39, 689826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 23, 28, 39, 689826, tzinfo=utc)),
        ),
    ]
